# Generated by Django 6.0.6 on 2026-07-05 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('expiration_date', models.DateField(verbose_name="Date d'expiration")),
                ('state', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('perime', 'Périmé')], default='disponible', max_length=20, verbose_name='État')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['expiration_date', 'name'],
            },
        ),
    ]
