# Generated by Django 6.0.6 on 2026-07-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_expiration', 'nom'], 'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['nom'], 'verbose_name': 'Entrepôt', 'verbose_name_plural': 'Entrepôts'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='expiration_date',
            new_name='date_expiration',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantite',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='capacity',
            new_name='capacite',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='localisation',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='name',
            new_name='nom',
        ),
    ]
